### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by 0oneo** [grpc/homebrew-grpc#108]
```bash
brew install --without-python google-protobuf
==> Installing google-protobuf from grpc/grpc
Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/grpc/homebrew-grpc/Formula/google-protobuf.rb:25:in `<class:GoogleProtobuf>'
Please report this to the grpc/grpc tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/grpc/homebrew-grpc/Formula/google-protobuf.rb:25:in `<class:GoogleProtobuf>'
Please report this to the grpc/grpc tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/grpc/homebrew-grpc/Formula/google-protobuf.rb:25:in `<class:GoogleProtobuf>'
Please report this to the grpc/grpc tap!

Warning: Calling fails_with :llvm is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/grpc/homebrew-grpc/Formula/google-protobuf.rb:25:in `<class:GoogleProtobuf>'
Please report this to the grpc/grpc tap!

==> Downloading https://github.com/google/protobuf/archive/v3.2.0.tar.gz
==> Downloading from https://codeload.github.com/google/protobuf/tar.gz/v3.2.0
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 2a25c2b71c707c5552ec9afdfb22532a93a339e1ca5d38f163fe4107af08c54c
Actual: a839d3f1519ff9d68ab908de5a0f269650ef1fc501c10f6eefd4cae51d29b86f
Archive: /Users/0oneo/Library/Caches/Homebrew/google-protobuf-3.2.0.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by bigodines** [comment]
I've worked around this issue by editing the formula SHA256

`brew edit google-protobuf`

replacing `2a25c2b71c707c5552ec9afdfb22532a93a339e1ca5d38f163fe4107af08c54c` with `a839d3f1519ff9d68ab908de5a0f269650ef1fc501c10f6eefd4cae51d29b86f`

this is a workaround, not a fix.

glhf

**Comment by louiewh** [comment]
Yes。I also happened to this problem

**Comment by louiewh** [comment]
bogon:grpc-java louie.wang$ brew install protobuf
==> Downloading https://github.com/google/protobuf/archive/v3.3.2.tar.gz
Already downloaded: /Users/louie.wang/Library/Caches/Homebrew/protobuf-3.3.2.tar.gz
Error: SHA256 mismatch
Expected: 8b8e442becbeff637f160c1ef4a3a56769c50ba7c9ff939ccc94086530ff00e4
Actual: e53fd5d514169dc80fb38673dc63f4048cebd3e524e49c1663428f89330bda56
Archive: /Users/louie.wang/Library/Caches/Homebrew/protobuf-3.3.2.tar.gz
To retry an incomplete download, remove the file above.

**Comment by stanley-cheung** [comment]
The "grpc" and the "protobuf" formulas are now part of homebrew-core. So there's no need to add this tap.
