### ISSUE TITLE
Linux python install looks OK 

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/homebrew-grpc#17]
```
stanleycheung@stanleycheung-test:~/python27$ virtualenv $HOME/python27
New python executable in /home/stanleycheung/python27/bin/python
Installing setuptools, pip...done.
stanleycheung@stanleycheung-test:~/python27$ source bin/activate
(python27)stanleycheung@stanleycheung-test:~/python27$ curl -fsSL https://goo.gl/getgrpc | bash -s python
==> Downloading http://pkgconfig.freedesktop.org/releases/pkg-config-0.28.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/home/stanleycheung/.linuxbrew/Cellar/pkg-config/0.28 --disable-host-tool -
==> make
==> make check
==> make install
/home/stanleycheung/.linuxbrew/Cellar/pkg-config/0.28: 10 files, 644K, built in 40 seconds
==> Installing openssl dependency: makedepend
==> Downloading http://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.5.tar.bz2
######################################################################## 100.0%
==> Downloading http://xorg.freedesktop.org/releases/individual/proto/xproto-7.0.25.tar.bz2
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/tmp/makedepend20150508-25435-lz3vof/makedepend-1.0.
==> make install
==> Downloading http://xorg.freedesktop.org/releases/individual/util/util-macros-1.18.0.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/tmp/makedepend20150508-25435-lz3vof/makedepend-1.0.5/xorg-macros
==> make install
==> ./configure --disable-silent-rules --prefix=/home/stanleycheung/.linuxbrew/Cellar/makedepend/1.0
==> make install
/home/stanleycheung/.linuxbrew/Cellar/makedepend/1.0.5: 7 files, 112K, built in 11 seconds
==> Installing openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2a.tar.gz
######################################################################## 100.0%
==> Downloading https://github.com/openssl/openssl/commit/6281abc796234.diff
######################################################################## 100.0%
==> Downloading https://github.com/openssl/openssl/commit/dfd3322d72a2.diff
######################################################################## 100.0%
==> Patching
patching file crypto/x509/x509_vfy.c
patching file crypto/x509/x509_vfy.c
patching file crypto/x509/x509_vfy.h
==> perl ./Configure --prefix=/home/stanleycheung/.linuxbrew/Cellar/openssl/1.0.2a-1 --openssldir=/h
==> make depend
==> make
==> make test
==> make install MANDIR=/home/stanleycheung/.linuxbrew/Cellar/openssl/1.0.2a-1/share/man MANSUFFIX=s
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /home/stanleycheung/.linuxbrew/etc/openssl/certs

and run
  /home/stanleycheung/.linuxbrew/opt/openssl/bin/c_rehash

==> Downloading http://curl.haxx.se/ca/cacert.pem
######################################################################## 100.0%
==> Summary
/home/stanleycheung/.linuxbrew/Cellar/openssl/1.0.2a-1: 463 files, 16M, built in 3.4 minutes
==> Tapping Homebrew/dupes
Cloning into '/home/stanleycheung/.linuxbrew/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 1673, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1673 (delta 1), reused 0 (delta 0), pack-reused 1667
Receiving objects: 100% (1673/1673), 342.32 KiB | 0 bytes/s, done.
Resolving deltas: 100% (922/922), done.
Checking connectivity... done.
Warning: Could not create link for homebrew/dupes/bzip2, as it
conflicts with Homebrew/homebrew/bzip2. You will need to use the
fully-qualified name when referring this formula, e.g.
  brew install homebrew/dupes/bzip2
Tapped 38 formulae (61 files, 708K)
==> Installing unzip from homebrew/homebrew-dupes
==> Downloading https://downloads.sourceforge.net/project/infozip/UnZip%206.x%20%28latest%29/UnZip%2
######################################################################## 100.0%
==> make -f unix/Makefile macosx
==> make prefix=/home/stanleycheung/.linuxbrew/Cellar/unzip/6.0 MANDIR=/home/stanleycheung/.linuxbre
/home/stanleycheung/.linuxbrew/Cellar/unzip/6.0: 14 files, 436K, built in 13 seconds
==> Installing dependencies for protobuf: autoconf, xz, automake, libtool
==> Installing protobuf dependency: autoconf
==> Downloading http://ftpmirror.gnu.org/autoconf/autoconf-2.69.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/home/stanleycheung/.linuxbrew/Cellar/autoconf/2.69
==> make install
/home/stanleycheung/.linuxbrew/Cellar/autoconf/2.69: 66 files, 3.2M, built in 7 seconds
==> Installing protobuf dependency: xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.1.tar.gz
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/home/stanleycheung/.linuxbrew/Cellar/xz/5.2.1
==> make install
/home/stanleycheung/.linuxbrew/Cellar/xz/5.2.1: 65 files, 1.9M, built in 37 seconds
==> Installing protobuf dependency: automake
==> Downloading http://ftpmirror.gnu.org/automake/automake-1.15.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/home/stanleycheung/.linuxbrew/Cellar/automake/1.15
==> make install
/home/stanleycheung/.linuxbrew/Cellar/automake/1.15: 130 files, 3.3M, built in 6 seconds
==> Installing protobuf dependency: libtool
==> Downloading http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/home/stanleycheung/.linuxbrew/Cellar/libtool/2.4.6 --program-prefix=g --en
==> make install
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.

==> Summary
/home/stanleycheung/.linuxbrew/Cellar/libtool/2.4.6: 69 files, 3.9M, built in 11 seconds
==> Installing protobuf
==> Downloading https://github.com/google/protobuf/archive/v3.0.0-alpha-2.tar.gz
######################################################################## 100.0%
==> ./autogen.sh
==> ./configure --prefix=/home/stanleycheung/.linuxbrew/Cellar/protobuf/3.0.0-alpha-2 --with-zlib
==> make
==> make install
==> Downloading https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf20150508-11861-gjae4i
==> Downloading https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.4.1.tar.
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf20150508-11861-gjae4i
==> Downloading https://pypi.python.org/packages/source/p/pytz/pytz-2014.10.tar.bz2
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf20150508-11861-gjae4i
==> Downloading https://pypi.python.org/packages/source/p/python-gflags/python-gflags-2.0.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf20150508-11861-gjae4i
==> Downloading https://pypi.python.org/packages/source/g/google-apputils/google-apputils-0.4.2.tar.
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf20150508-11861-gjae4i
==> python -c import setuptools... --no-user-cfg install --prefix=/home/stanleycheung/.linuxbrew/Cel
google/protobuf/pyext/descriptor.cc:33:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: command '/usr/bin/gcc-4.8' failed with exit status 1

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
New formula: protobuf-swift installation using homebrew (https://github.com/Homebrew/homebrew/pull/39101)
protobuf-c needs c++11 option (https://github.com/Homebrew/homebrew/issues/30320)
==> Tapping grpc/grpc
Cloning into '/home/stanleycheung/.linuxbrew/Library/Taps/grpc/homebrew-grpc'...
remote: Counting objects: 141, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 141 (delta 5), reused 0 (delta 0), pack-reused 124
Receiving objects: 100% (141/141), 20.55 KiB | 0 bytes/s, done.
Resolving deltas: 100% (44/44), done.
Checking connectivity... done.
Tapped 1 formula (27 files, 220K)
==> Installing grpc from grpc/homebrew-grpc
==> Installing grpc dependency: protobuf
==> Downloading https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/home/stanleycheung/.linuxbrew/Cellar/protobuf/2.6.1 --with-zlib
==> make
==> make install
==> Downloading https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
Already downloaded: /home/stanleycheung/.cache/Homebrew/protobuf--six-1.9.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf20150508-21457-1aw1le
==> Downloading https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.4.1.tar.
Already downloaded: /home/stanleycheung/.cache/Homebrew/protobuf--python-dateutil-2.4.1.tar.bz2
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf20150508-21457-1aw1le
==> Downloading https://pypi.python.org/packages/source/p/pytz/pytz-2014.10.tar.bz2
Already downloaded: /home/stanleycheung/.cache/Homebrew/protobuf--pytz-2014.10.tar.bz2
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf20150508-21457-1aw1le
==> Downloading https://pypi.python.org/packages/source/p/python-gflags/python-gflags-2.0.tar.gz
Already downloaded: /home/stanleycheung/.cache/Homebrew/protobuf--python-gflags-2.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf20150508-21457-1aw1le
==> Downloading https://pypi.python.org/packages/source/g/google-apputils/google-apputils-0.4.2.tar.
Already downloaded: /home/stanleycheung/.cache/Homebrew/protobuf--google-apputils-0.4.2.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf20150508-21457-1aw1le
==> python -c import setuptools... --no-user-cfg install --prefix=/home/stanleycheung/.linuxbrew/Cel
google/protobuf/pyext/descriptor.cc:33:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: command '/usr/bin/gcc-4.8' failed with exit status 1

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
New formula: protobuf-swift installation using homebrew (https://github.com/Homebrew/homebrew/pull/39101)
protobuf-c needs c++11 option (https://github.com/Homebrew/homebrew/issues/30320)
installing grpc python
/home/stanleycheung/python27/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting grpcio
/home/stanleycheung/python27/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading grpcio-0.5.0a2.tar.gz (88kB)
    100% |████████████████████████████████| 90kB 1.7MB/s 
Collecting enum34==1.0.4 (from grpcio)
  Downloading enum34-1.0.4.tar.gz
Collecting futures==2.2.0 (from grpcio)
  Downloading futures-2.2.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0-alpha-1 (from grpcio)
  Downloading protobuf-3.0.0-alpha-1.tar.gz (193kB)
    100% |████████████████████████████████| 196kB 2.3MB/s 
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./lib/python2.7/site-packages (from protobuf==3.0.0-alpha-1->grpcio)
Installing collected packages: enum34, futures, protobuf, grpcio
  Running setup.py install for enum34
  Running setup.py install for protobuf
  Running setup.py install for grpcio
    Complete output from command /home/stanleycheung/python27/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-aXdxQQ/grpcio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0a5wc7-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/stanleycheung/python27/include/site/python2.7/grpcio:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/grpc
    copying grpc/__init__.py -> build/lib.linux-x86_64-2.7/grpc
    creating build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/_face_test_case.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/_links_test.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/_datatypes.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/_lonely_rear_link_test.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/fore.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/_future_invocation_asynchronous_event_service_test.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/_event_invocation_synchronous_event_service_test.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/_blocking_invocation_inline_service_test.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/_c_test.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/__init__.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/rear.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/_low.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/_proto_scenarios.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/_common.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/_low_test.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    copying grpc/_adapter/_test_links.py -> build/lib.linux-x86_64-2.7/grpc/_adapter
    creating build/lib.linux-x86_64-2.7/grpc/_junkdrawer
    copying grpc/_junkdrawer/math_pb2.py -> build/lib.linux-x86_64-2.7/grpc/_junkdrawer
    copying grpc/_junkdrawer/stock_pb2.py -> build/lib.linux-x86_64-2.7/grpc/_junkdrawer
    copying grpc/_junkdrawer/__init__.py -> build/lib.linux-x86_64-2.7/grpc/_junkdrawer
    creating build/lib.linux-x86_64-2.7/grpc/early_adopter
    copying grpc/early_adopter/implementations_test.py -> build/lib.linux-x86_64-2.7/grpc/early_adopter
    copying grpc/early_adopter/__init__.py -> build/lib.linux-x86_64-2.7/grpc/early_adopter
    copying grpc/early_adopter/implementations.py -> build/lib.linux-x86_64-2.7/grpc/early_adopter
    creating build/lib.linux-x86_64-2.7/grpc/framework
    copying grpc/framework/__init__.py -> build/lib.linux-x86_64-2.7/grpc/framework
    creating build/lib.linux-x86_64-2.7/grpc/framework/alpha
    copying grpc/framework/alpha/interfaces.py -> build/lib.linux-x86_64-2.7/grpc/framework/alpha
    copying grpc/framework/alpha/exceptions.py -> build/lib.linux-x86_64-2.7/grpc/framework/alpha
    copying grpc/framework/alpha/_face_utilities.py -> build/lib.linux-x86_64-2.7/grpc/framework/alpha
    copying grpc/framework/alpha/__init__.py -> build/lib.linux-x86_64-2.7/grpc/framework/alpha
    copying grpc/framework/alpha/_reexport.py -> build/lib.linux-x86_64-2.7/grpc/framework/alpha
    copying grpc/framework/alpha/utilities.py -> build/lib.linux-x86_64-2.7/grpc/framework/alpha
    creating build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/_interfaces.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/implementations_test.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/null.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/interfaces.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/_ingestion.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/_expiration.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/_constants.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/exceptions.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/_ends.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/interfaces_test_case.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/_emission.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/_context.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/__init__.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/_cancellation.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/in_memory.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/_termination.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/implementations.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/_transmission.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/util.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    copying grpc/framework/base/_reception.py -> build/lib.linux-x86_64-2.7/grpc/framework/base
    creating build/lib.linux-x86_64-2.7/grpc/framework/common
    copying grpc/framework/common/__init__.py -> build/lib.linux-x86_64-2.7/grpc/framework/common
    copying grpc/framework/common/cardinality.py -> build/lib.linux-x86_64-2.7/grpc/framework/common
    copying grpc/framework/common/style.py -> build/lib.linux-x86_64-2.7/grpc/framework/common
    creating build/lib.linux-x86_64-2.7/grpc/framework/face
    copying grpc/framework/face/_test_case.py -> build/lib.linux-x86_64-2.7/grpc/framework/face
    copying grpc/framework/face/future_invocation_asynchronous_event_service_test.py -> build/lib.linux-x86_64-2.7/grpc/framework/face
    copying grpc/framework/face/_service.py -> build/lib.linux-x86_64-2.7/grpc/framework/face
    copying grpc/framework/face/interfaces.py -> build/lib.linux-x86_64-2.7/grpc/framework/face
    copying grpc/framework/face/_calls.py -> build/lib.linux-x86_64-2.7/grpc/framework/face
    copying grpc/framework/face/exceptions.py -> build/lib.linux-x86_64-2.7/grpc/framework/face
    copying grpc/framework/face/_control.py -> build/lib.linux-x86_64-2.7/grpc/framework/face
    copying grpc/framework/face/__init__.py -> build/lib.linux-x86_64-2.7/grpc/framework/face
    copying grpc/framework/face/event_invocation_synchronous_event_service_test.py -> build/lib.linux-x86_64-2.7/grpc/framework/face
    copying grpc/framework/face/implementations.py -> build/lib.linux-x86_64-2.7/grpc/framework/face
    copying grpc/framework/face/utilities.py -> build/lib.linux-x86_64-2.7/grpc/framework/face
    copying grpc/framework/face/demonstration.py -> build/lib.linux-x86_64-2.7/grpc/framework/face
    copying grpc/framework/face/blocking_invocation_inline_service_test.py -> build/lib.linux-x86_64-2.7/grpc/framework/face
    creating build/lib.linux-x86_64-2.7/grpc/framework/face/testing
    copying grpc/framework/face/testing/event_invocation_synchronous_event_service_test_case.py -> build/lib.linux-x86_64-2.7/grpc/framework/face/testing
    copying grpc/framework/face/testing/stock_service.py -> build/lib.linux-x86_64-2.7/grpc/framework/face/testing
    copying grpc/framework/face/testing/digest.py -> build/lib.linux-x86_64-2.7/grpc/framework/face/testing
    copying grpc/framework/face/testing/interfaces.py -> build/lib.linux-x86_64-2.7/grpc/framework/face/testing
    copying grpc/framework/face/testing/service.py -> build/lib.linux-x86_64-2.7/grpc/framework/face/testing
    copying grpc/framework/face/testing/coverage.py -> build/lib.linux-x86_64-2.7/grpc/framework/face/testing
    copying grpc/framework/face/testing/base_util.py -> build/lib.linux-x86_64-2.7/grpc/framework/face/testing
    copying grpc/framework/face/testing/control.py -> build/lib.linux-x86_64-2.7/grpc/framework/face/testing
    copying grpc/framework/face/testing/__init__.py -> build/lib.linux-x86_64-2.7/grpc/framework/face/testing
    copying grpc/framework/face/testing/blocking_invocation_inline_service_test_case.py -> build/lib.linux-x86_64-2.7/grpc/framework/face/testing
    copying grpc/framework/face/testing/test_case.py -> build/lib.linux-x86_64-2.7/grpc/framework/face/testing
    copying grpc/framework/face/testing/callback.py -> build/lib.linux-x86_64-2.7/grpc/framework/face/testing
    copying grpc/framework/face/testing/future_invocation_asynchronous_event_service_test_case.py -> build/lib.linux-x86_64-2.7/grpc/framework/face/testing
    copying grpc/framework/face/testing/serial.py -> build/lib.linux-x86_64-2.7/grpc/framework/face/testing
    creating build/lib.linux-x86_64-2.7/grpc/framework/foundation
    copying grpc/framework/foundation/stream_testing.py -> build/lib.linux-x86_64-2.7/grpc/framework/foundation
    copying grpc/framework/foundation/abandonment.py -> build/lib.linux-x86_64-2.7/grpc/framework/foundation
    copying grpc/framework/foundation/stream_util.py -> build/lib.linux-x86_64-2.7/grpc/framework/foundation
    copying grpc/framework/foundation/activated.py -> build/lib.linux-x86_64-2.7/grpc/framework/foundation
    copying grpc/framework/foundation/callable_util.py -> build/lib.linux-x86_64-2.7/grpc/framework/foundation
    copying grpc/framework/foundation/_later_test.py -> build/lib.linux-x86_64-2.7/grpc/framework/foundation
    copying grpc/framework/foundation/stream.py -> build/lib.linux-x86_64-2.7/grpc/framework/foundation
    copying grpc/framework/foundation/_timer_future.py -> build/lib.linux-x86_64-2.7/grpc/framework/foundation
    copying grpc/framework/foundation/later.py -> build/lib.linux-x86_64-2.7/grpc/framework/foundation
    copying grpc/framework/foundation/logging_pool.py -> build/lib.linux-x86_64-2.7/grpc/framework/foundation
    copying grpc/framework/foundation/__init__.py -> build/lib.linux-x86_64-2.7/grpc/framework/foundation
    copying grpc/framework/foundation/future.py -> build/lib.linux-x86_64-2.7/grpc/framework/foundation
    copying grpc/framework/foundation/_logging_pool_test.py -> build/lib.linux-x86_64-2.7/grpc/framework/foundation
    running build_ext
    building 'grpc._adapter._c' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/grpc
    creating build/temp.linux-x86_64-2.7/grpc/_adapter
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -I/home/stanleycheung/.linuxbrew/include -fPIC -I. -I/usr/include/python2.7 -c grpc/_adapter/_c.c -o build/temp.linux-x86_64-2.7/grpc/_adapter/_c.o
    grpc/_adapter/_c.c:34:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
    Command "/home/stanleycheung/python27/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-aXdxQQ/grpcio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0a5wc7-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/stanleycheung/python27/include/site/python2.7/grpcio" failed with error code 1 in /tmp/pip-build-aXdxQQ/grpcio
(python27)stanleycheung@stanleycheung-test:~/python27$ 
```

**Comment by stanley-cheung** [comment]
Looks like we need one more dependency

```
sudo apt-get install python-dev
```

After that the installation looks successful

```
(python27)stanleycheung@stanleycheung-test:~/python27$ curl -fsSL https://goo.gl/getgrpc | bash -s python
pkg-config is already installed
openssl is already installed
==> Downloading https://github.com/google/protobuf/archive/v3.0.0-alpha-2.tar.gz
Already downloaded: /home/stanleycheung/.cache/Homebrew/protobuf-3.0.0-alpha-2.tar.gz
==> ./autogen.sh
==> ./configure --prefix=/home/stanleycheung/.linuxbrew/Cellar/protobuf/3.0.0-alpha-2 --with-zlib
==> make
==> make install
==> Downloading https://pypi.python.org/packages/source/s/six/six-1.9.0.tar.gz
Already downloaded: /home/stanleycheung/.cache/Homebrew/protobuf--six-1.9.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf20150508-13202-1jjnsf
==> Downloading https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.4.1.tar.
Already downloaded: /home/stanleycheung/.cache/Homebrew/protobuf--python-dateutil-2.4.1.tar.bz2
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf20150508-13202-1jjnsf
==> Downloading https://pypi.python.org/packages/source/p/pytz/pytz-2014.10.tar.bz2
Already downloaded: /home/stanleycheung/.cache/Homebrew/protobuf--pytz-2014.10.tar.bz2
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf20150508-13202-1jjnsf
==> Downloading https://pypi.python.org/packages/source/p/python-gflags/python-gflags-2.0.tar.gz
Already downloaded: /home/stanleycheung/.cache/Homebrew/protobuf--python-gflags-2.0.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf20150508-13202-1jjnsf
==> Downloading https://pypi.python.org/packages/source/g/google-apputils/google-apputils-0.4.2.tar.
Already downloaded: /home/stanleycheung/.cache/Homebrew/protobuf--google-apputils-0.4.2.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/protobuf20150508-13202-1jjnsf
==> python -c import setuptools... --no-user-cfg install --prefix=/home/stanleycheung/.linuxbrew/Cel
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
==> Caveats
Editor support and examples have been installed to:
  /home/stanleycheung/.linuxbrew/Cellar/protobuf/3.0.0-alpha-2/share/doc/protobuf


Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p 
  echo 'import site; site.addsitedir("/home/stanleycheung/.linuxbrew/lib/python2.7/site-packages")' >> homebrew.pth
==> Summary
/home/stanleycheung/.linuxbrew/Cellar/protobuf/3.0.0-alpha-2: 169 files, 12M, built in 3.2 minutes
Warning: Already tapped!
==> Installing grpc from grpc/homebrew-grpc
==> Cloning https://github.com/grpc/grpc.git
Cloning into '/home/stanleycheung/.cache/Homebrew/grpc--git'...
remote: Counting objects: 1499, done.
remote: Compressing objects: 100% (1235/1235), done.
remote: Total 1499 (delta 678), reused 462 (delta 201), pack-reused 0
Receiving objects: 100% (1499/1499), 1.67 MiB | 0 bytes/s, done.
Resolving deltas: 100% (678/678), done.
Checking connectivity... done.
==> Checking out branch master
==> make install prefix=/home/stanleycheung/.linuxbrew/Cellar/grpc/HEAD
/home/stanleycheung/.linuxbrew/Cellar/grpc/HEAD: 85 files, 7.4M, built in 80 seconds
installing grpc python
Collecting grpcio
/home/stanleycheung/python27/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached grpcio-0.5.0a2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): enum34==1.0.4 in ./lib/python2.7/site-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): futures==2.2.0 in ./lib/python2.7/site-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): protobuf==3.0.0-alpha-1 in ./lib/python2.7/site-packages (from grpcio)
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./lib/python2.7/site-packages (from protobuf==3.0.0-alpha-1->grpcio)
Installing collected packages: grpcio
  Running setup.py install for grpcio
Successfully installed grpcio-0.5.0a2
(python27)stanleycheung@stanleycheung-test:~/python27$
```
