### ISSUE TITLE
Installation is failing with an error referring to zlib

### ISSUE THREAD

**Issue by murgatroid99** [grpc/homebrew-grpc#65]
This was first reported in grpc/grpc#3874. The user attempted to follow the Mac Node.js installation instructions by running

``` sh
curl -fsSL https://goo.gl/getgrpc | bash -s nodejs
```

and they got the output

```
Error: undefined method `desc' for Formulary::Formulae::Zlib:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-dupes/zlib.rb:2:in `<class:Zlib>'
/usr/local/Library/Taps/homebrew/homebrew-dupes/zlib.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:135:in `<main>'
```

**Comment by oscar608** [comment]
```

whwdeMacBook-Pro:~ whw$ sudo chown -R whw  /usr/local/lib/
whwdeMacBook-Pro:~ whw$ brew link google-protobuf
Linking /usr/local/Cellar/google-protobuf/3.0.0-beta-1... 14 symlinks created
whwdeMacBook-Pro:~ whw$ curl -fsSL https://goo.gl/getgrpc | bash -s nodejs
zlib is already installed
openssl is already installed
google-protobuf is already installed
==> Installing grpc from grpc/homebrew-grpc
==> Installing dependencies for grpc/grpc/grpc: openssl, pkg-config
==> Installing grpc/grpc/grpc dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2d_1.yosemite.b
######################################################################## 100.0%
==> Pouring openssl-1.0.2d_1.yosemite.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2d_1: 464 files, 18M
==> Installing grpc/grpc/grpc dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.28.yosemite.bo
######################################################################## 100.0%
==> Pouring pkg-config-0.28.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.28: 10 files, 612K
==> Installing grpc/grpc/grpc
==> Downloading https://github.com/grpc/grpc/archive/release-0_11_0.tar.gz
==> Downloading from https://codeload.github.com/grpc/grpc/tar.gz/release-0_11_0
######################################################################## 100.0%
==> make install install_grpc_csharp_ext prefix=/usr/local/Cellar/grpc/0.11.0
🍺  /usr/local/Cellar/grpc/0.11.0: 100 files, 4.2M, built in 38 seconds
installing grpc nodejs
-
> grpc@0.11.1 install /usr/local/lib/node_modules/grpc
> node-gyp rebuild

  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
  CXX(target) Release/obj.target/grpc/ext/call.o
  CXX(target) Release/obj.target/grpc/ext/channel.o
  CXX(target) Release/obj.target/grpc/ext/completion_queue_async_worker.o
  CXX(target) Release/obj.target/grpc/ext/credentials.o
  CXX(target) Release/obj.target/grpc/ext/node_grpc.o
  CXX(target) Release/obj.target/grpc/ext/server.o
  CXX(target) Release/obj.target/grpc/ext/server_credentials.o
  CXX(target) Release/obj.target/grpc/ext/timeval.o
  SOLINK_MODULE(target) Release/grpc.node
  SOLINK_MODULE(target) Release/grpc.node: Finished
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.3.1
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires uid-number@'0.0.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/uid-number,
npm WARN unmet dependency which is version 0.0.6
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires semver@'2 || 3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.3.1
grpc@0.11.1 /usr/local/lib/node_modules/grpc
├── bindings@1.2.1
├── nan@2.1.0
├── lodash@3.10.1
└── protobufjs@4.1.2 (ascli@1.0.0, bytebuffer@4.1.0, glob@5.0.15, yargs@3.29.0)


```

**Comment by oscar608** [comment]
it is ok now

**Comment by oscar608** [comment]
i do not know  why it is ok:(

**Comment by oscar608** [comment]
```
whwdeMacBook-Pro:grpc whw$ git checkout origin/release-0_11
Note: checking out 'origin/release-0_11'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 432ca59... Merge pull request #3817 from jcanizales/make-testing-sane
whwdeMacBook-Pro:grpc whw$ cd examples
whwdeMacBook-Pro:examples whw$ cd node
whwdeMacBook-Pro:node whw$ npm install
npm WARN package.json grpc-demo@0.11.0 No repository field.
|
> grpc@0.11.1 install /Users/whw/grpc/examples/node/node_modules/grpc
> node-gyp rebuild

  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
  CXX(target) Release/obj.target/grpc/ext/call.o
  CXX(target) Release/obj.target/grpc/ext/channel.o
  CXX(target) Release/obj.target/grpc/ext/completion_queue_async_worker.o
  CXX(target) Release/obj.target/grpc/ext/credentials.o
  CXX(target) Release/obj.target/grpc/ext/node_grpc.o
  CXX(target) Release/obj.target/grpc/ext/server.o
  CXX(target) Release/obj.target/grpc/ext/server_credentials.o
  CXX(target) Release/obj.target/grpc/ext/timeval.o
  SOLINK_MODULE(target) Release/grpc.node
  SOLINK_MODULE(target) Release/grpc.node: Finished
minimist@1.2.0 node_modules/minimist

underscore@1.8.3 node_modules/underscore

async@0.9.2 node_modules/async

grpc@0.11.1 node_modules/grpc
├── bindings@1.2.1
├── nan@2.1.0
├── lodash@3.10.1
└── protobufjs@4.1.2 (ascli@1.0.0, bytebuffer@4.1.0, glob@5.0.15, yargs@3.29.0)


```

**Comment by oscar608** [comment]
it is ok
